# Config dataset for yolo model
model: yolo11m # [yolov8, yolov11]
mode: yolo  #[yolo, coco]
weight: yolo11m.pt

cfg_file: ./config/default.yaml

directory_path: nighttime
max_per_class: 100
n_folds: 5
kfolds_dir: kfolds
selected_classes: ['bus', 'truck']
objects_lib_dir: objects_lib
class_name: ['motorcycle', 'car', 'bus', 'truck']
# Train Hyperparameters
imgsz: 640
batch: 16
epochs: 20
num_workers: 4
lr: 0.001

debug: false
use_kfolds: true
# lr:

output_dir: ./outputs